
name: flutter_push_demo
description: A simple push notification demo app

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.1

flutter:
  uses-material-design: true
